config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('alexa', views.alexa_page_view, name='alexa'),
    path('aspirador', views.aspirador_page_view, name='aspirador'),
    path('bimby', views.bimby_page_view, name='bimby')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render


def home_page_view(request):
    return render(request, 'website/home.html')


def alexa_page_view(request):
    return render(request, 'website/alexa.html')


def aspirador_page_view(request):
    return render(request, 'website/aspirador.html')


def bimby_page_view(request):
    return render(request, 'website/bimby.html')

website/templates/website/alexa.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Alexa</h3>
    <p>     A <a href="https://www.amazon.com/s?k=alexa&__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss">Amazon Alexa</a> é uma assistente virtual desenvolvida pela Amazon capaz de interagir com voz, reproduzir música, fazer
        listas de afazeres e outras informações em tempo real além de controlar sistemas e aparelhos inteligentes e conectados. </p>
{% endblock %}
{% block aside %}
     {% load static %}
    <img style= " height: 250px" src="{% static 'website/images/alexa.png' %}">
{% endblock %}

website/templates/website/aspirador.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Robô Aspirador</h3>
    <p>O <a href="https://pt.aliexpress.com/i/33024930650.html">robô aspirador</a>, é um robô que limpa sua casa automaticamente,
        como um aspirador de pó.</p>
{% endblock %}
{% block aside %}
    {% load static %}
    <img style= "width: 300px; height: 280px"src="{% static 'website/images/roboAspirador.jpg' %}">
{% endblock %}

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <header class="jumbotron text-center">
        <h1>Melhores Artigos Para Casa</h1>
        <p>Veja aqui os melhores artigos para ter em sua casa de modo a facilitar a sua vida</p>
        <nav>
            <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
            <a href="{% url 'website:alexa' %}" class="btn btn-info">Alexa</a>
            <a href="{% url 'website:aspirador' %}" class="btn btn-info">Robô Aspirador</a>
            <a href="{% url 'website:bimby' %}" class="btn btn-info">Bimby</a>
        </nav>
    </header>
    <center>
    <article class="container">
        <main class="col-sm-6">

	{% block main %}
    {% endblock main %}

        </main>
    </center>
    <center>
        <aside class="col-sm-6">
            {% block aside %}
	        {% endblock aside %}
        </aside>
    </center>
    </article>
    <footer>Se tiver estes produtos vai ser tão feliz como a familia que aparece na aba Home</footer>

</body>
</html>

website/templates/website/bimby.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Bimby</h3>
    <p>A <a href="https://bimby.vorwerk.pt/comprar-a-bimbyr/?gclid=CjwKCAjw1uiEBhBzEiwAO9B_HZwplw8nceeqcgKfYWOndlLTpH6-Ca7uEJ2sjZnTCA7_s0Dp078nABoCRX8QAvD_BwE">
        Bimby</a> é um robot de cozinha, que serve para pulverizar,
        picar, bater massas, cozinhar a vapor ou cozinhar directamente os alimentos.</p>
{% endblock %}
{% block aside %}
     {% load static %}
    <img style="width: 400px; height: 280px" src="{% static 'website/images/bimby.jpg' %}">
{% endblock %}

website/templates/website/home.html
<!-- home.html -->
{% extends 'website/base.html' %}
{% block main %}
    <h3>Os 3 melhores artigos para sua casa</h3>
    <p>Ao comprar estes produtos vai ter a sua vida facilitada a 500% </p>
{% endblock %}
{% block aside %}
    <img   src="lab6/website/static/website/images/familiaFeliz.jpeg">
{% endblock %}